;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-append
        evil-backward-char
        evil-delete
        evil-delete-backward-char-and-join
        evil-delete-char
        evil-digit-argument-or-evil-beginning-of-line
        evil-end-of-line
        evil-force-normal-state
        evil-forward-char
        evil-insert
        evil-normal-state
        evil-paste-after
        evil-previous-line
        evil-replace
        evil-scroll-line-down
        evil-search-forward
        evil-visual-char
        evil-yank
        hydra-global-all/body
        ibuffer-do-kill-on-deletion-marks
        ibuffer-mark-for-delete
        smex
        undefined
        ))

(setq mc/cmds-to-run-once
      '(
        sp-backward-delete-char
        ))
